name: dart_rxdart_streams
description: RxDart practicing.
version: 1.0.0
repository: https://github.com/AmangeldiyevSultan

environment:
  sdk: ^3.0.6

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
